/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

declare const self: ServiceWorkerGlobalScope

// Extend ServiceWorker types
interface NotificationAction {
  action: string
  title: string
  icon?: string
}

interface SyncEvent extends Event {
  tag: string
  waitUntil(promise: Promise<void>): void
}

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// Take control of clients immediately
clientsClaim()

// ============================================================================
// PUSH NOTIFICATIONS
// ============================================================================

interface PushPayload {
  title: string
  body: string
  icon?: string
  badge?: string
  image?: string
  tag?: string
  requireInteraction?: boolean
  data?: {
    url?: string
    notificationId?: string
    type?: 'mention' | 'reply' | 'like' | 'follow' | 'repost' | 'quote'
  }
}

self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return

  try {
    const data: PushPayload = event.data.json()

    // Extended notification options with actions support
    interface ExtendedNotificationOptions extends NotificationOptions {
      actions?: NotificationAction[]
    }

    const notificationOptions: ExtendedNotificationOptions = {
      body: data.body,
      icon: data.icon ?? '/icon-192.png',
      badge: data.badge ?? '/icon-72.png',
      tag: data.tag ?? 'default',
      requireInteraction: data.requireInteraction ?? false,
      data: data.data,
      // Action buttons for quick interactions
      actions: data.data?.type === 'mention' || data.data?.type === 'reply'
        ? [
            { action: 'open', title: 'View' },
            { action: 'dismiss', title: 'Dismiss' },
          ]
        : data.data?.type === 'like' || data.data?.type === 'follow'
          ? [
              { action: 'open', title: 'View Profile' },
              { action: 'dismiss', title: 'Dismiss' },
            ]
          : undefined,
    }

    event.waitUntil(
      self.registration.showNotification(data.title, notificationOptions)
    )
  } catch (err) {
    console.error('[SW] Failed to show notification:', err)
  }
})

// Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()

  const notificationData = event.notification.data
  const action = event.action

  if (action === 'dismiss') {
    return
  }

  // Default to opening the URL from notification data
  const urlToOpen = notificationData?.url ?? '/'

  event.waitUntil(
    (async () => {
      // Try to find an existing client window
      const clientList = await self.clients.matchAll({
        type: 'window',
        includeUncontrolled: true,
      })

      // If we have a client, focus it and navigate
      for (const client of clientList) {
        if (client.url && 'focus' in client) {
          await client.focus()
          // Post message to navigate
          client.postMessage({
            type: 'NAVIGATE',
            url: urlToOpen,
          })
          return
        }
      }

      // Otherwise, open a new window
      await self.clients.openWindow(urlToOpen)
    })()
  )
})

// Handle notification close (dismissal)
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  // Optionally track dismissals for analytics
  console.log('[SW] Notification closed:', event.notification.tag)
})

// ============================================================================
// MESSAGE HANDLING (from main app)
// ============================================================================

self.addEventListener('message', (event) => {
  const { type } = event.data || {}

  switch (type) {
    case 'SKIP_WAITING':
      self.skipWaiting()
      break

    case 'GET_VERSION':
      // Respond with the current service worker version
      event.ports[0]?.postMessage({
        type: 'VERSION',
        version: '1.0.0', // Could be dynamic based on build
      })
      break

    case 'SHOW_NOTIFICATION':
      // Show local notification from main thread (polling-based)
      {
        const { title, body, icon, data } = event.data
        void self.registration.showNotification(title, {
          body,
          icon: icon ?? '/icon-192.png',
          badge: '/icon-72.png',
          tag: data?.url ?? 'default',
          data,
          actions: data?.type === 'mention' || data?.type === 'reply'
            ? [
                { action: 'open', title: 'View' },
                { action: 'dismiss', title: 'Dismiss' },
              ]
            : data?.type === 'like' || data?.type === 'follow'
              ? [
                  { action: 'open', title: 'View Profile' },
                  { action: 'dismiss', title: 'Dismiss' },
                ]
              : undefined,
        })
      }
      break

    default:
      break
  }
})

// ============================================================================
// BACKGROUND SYNC (for offline support)
// ============================================================================

self.addEventListener('sync', ((event: SyncEvent) => {
  if (event.tag === 'sync-notifications') {
    event.waitUntil(syncNotifications())
  }
}) as EventListener)

async function syncNotifications(): Promise<void> {
  // This would sync with Bluesky API when back online
  // Implementation depends on your offline strategy
  console.log('[SW] Syncing notifications...')
}

// Log activation
self.addEventListener('activate', () => {
  console.log('[SW] Service Worker activated')
})

// Log installation
self.addEventListener('install', () => {
  console.log('[SW] Service Worker installing...')
})
