/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { clientsClaim } from 'workbox-core'
import type { PrecacheEntry } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

// Extend ServiceWorker types
interface NotificationAction {
  action: string
  title: string
  icon?: string
}

interface ExtendedNotificationOptions extends NotificationOptions {
  actions?: NotificationAction[]
}

interface SyncEvent extends Event {
  tag: string
  waitUntil(promise: Promise<void>): void
}

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Clean up old caches
cleanupOutdatedCaches()

// Take control of clients immediately
clientsClaim()

// ============================================================================
// RUNTIME CACHING
// ============================================================================
// NOTE: vite-plugin-pwa's `workbox.runtimeCaching` option is only honored with
// `strategies: 'generateSW'` — this project uses `injectManifest` (src/sw.ts),
// so runtime routes must be registered here. Without these, the lazy route
// chunks excluded from the precache manifest (see vite.config.ts globIgnores)
// and all remote images are network-only, breaking the installed PWA offline.

// Media/avatars from the Bluesky CDN.
registerRoute(
  ({ url }) => url.origin === 'https://cdn.bsky.app',
  new CacheFirst({
    cacheName: 'artsky-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
      }),
    ],
  }),
)

// Lazy route chunks not covered by the precache manifest: serve cached copy
// instantly, refresh in the background (hashed URLs make stale copies safe).
registerRoute(
  ({ request, url }) =>
    request.mode !== 'navigate' && /\/assets\/[^/]+\.(?:js|css)$/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: 'artsky-assets-runtime',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 120,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  }),
)

// App-shell fallback: serve the precached index.html for SPA navigations so deep
// links and route URLs work offline (the router renders from cached data).
// share-target is denied because the POST share launch is handled by the fetch
// listener below (a navigation request would otherwise be answered here first).
const indexEntry = self.__WB_MANIFEST.find(
  (entry): entry is PrecacheEntry =>
    typeof entry === 'object' && /(^|\/)index\.html$/.test(entry.url),
)
if (indexEntry) {
  registerRoute(
    new NavigationRoute(createHandlerBoundToURL(indexEntry.url), {
      denylist: [/share-target$/],
    }),
  )
}

// ============================================================================
// WEB SHARE TARGET
// ============================================================================
// The manifest declares `./share-target` (POST, multipart/form-data). The share
// launches the app with that POST; we stash the payload in a cache and redirect
// to `/?share=1`, where the app reads it back and opens the composer prefilled.

const SHARE_CACHE = 'artsky-share-target'
const SHARE_PAYLOAD_KEY = 'share-payload'

interface ShareTargetPayload {
  title: string
  text: string
  url: string
  fileKeys: string[]
}

self.addEventListener('fetch', ((event: FetchEvent) => {
  if (event.request.method !== 'POST') return
  const url = new URL(event.request.url)
  if (!/(^|\/)share-target$/.test(url.pathname)) return
  event.respondWith(handleShareTargetPost(event.request))
}) as EventListener)

async function handleShareTargetPost(request: Request): Promise<Response> {
  const redirectHome = () =>
    Response.redirect(new URL('./', self.registration.scope).href, 303)
  try {
    const formData = await request.formData()
    const cache = await caches.open(SHARE_CACHE)
    // Drop any previous (unconsumed) payload so the client reads only this share.
    for (const key of await cache.keys()) {
      if (new URL(key.url).pathname.endsWith(SHARE_PAYLOAD_KEY) || key.url.includes('share-file-')) {
        await cache.delete(key)
      }
    }
    const stamp = Date.now()
    const fileKeys: string[] = []
    const files = formData.getAll('media').filter((value): value is File => value instanceof File)
    for (let i = 0; i < files.length; i += 1) {
      const file = files[i]!
      const key = `share-file-${stamp}-${i}`
      await cache.put(
        new URL(key, self.registration.scope).href,
        new Response(file, { headers: { 'content-type': file.type || 'application/octet-stream' } }),
      )
      fileKeys.push(new URL(key, self.registration.scope).href)
    }
    const payload: ShareTargetPayload = {
      title: String(formData.get('title') ?? ''),
      text: String(formData.get('text') ?? ''),
      url: String(formData.get('url') ?? ''),
      fileKeys,
    }
    await cache.put(
      new URL(SHARE_PAYLOAD_KEY, self.registration.scope).href,
      new Response(JSON.stringify(payload), { headers: { 'content-type': 'application/json' } }),
    )
    return Response.redirect(new URL('./?share=1', self.registration.scope).href, 303)
  } catch (err) {
    console.error('[SW] share-target handling failed:', err)
    return redirectHome()
  }
}

// ============================================================================
// PUSH NOTIFICATIONS
// ============================================================================

interface PushPayload {
  title: string
  body: string
  icon?: string
  badge?: string
  image?: string
  tag?: string
  requireInteraction?: boolean
  data?: {
    url?: string
    notificationId?: string
    type?: 'mention' | 'reply' | 'like' | 'follow' | 'repost' | 'quote'
  }
}

self.addEventListener('push', (event: PushEvent) => {
  if (!event.data) return

  try {
    const data: PushPayload = event.data.json()

    const notificationOptions: ExtendedNotificationOptions = {
      body: data.body,
      icon: data.icon ?? '/icon-192.png',
      badge: data.badge ?? '/icon-72.png',
      tag: data.tag ?? 'default',
      requireInteraction: data.requireInteraction ?? false,
      data: data.data,
      // Action buttons for quick interactions
      actions: data.data?.type === 'mention' || data.data?.type === 'reply'
        ? [
            { action: 'open', title: 'View' },
            { action: 'dismiss', title: 'Dismiss' },
          ]
        : data.data?.type === 'like' || data.data?.type === 'follow'
          ? [
              { action: 'open', title: 'View Profile' },
              { action: 'dismiss', title: 'Dismiss' },
            ]
          : undefined,
    }

    event.waitUntil(
      self.registration.showNotification(data.title, notificationOptions)
    )
  } catch (err) {
    console.error('[SW] Failed to show notification:', err)
  }
})

// Handle notification clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()

  const notificationData = event.notification.data
  const action = event.action

  if (action === 'dismiss') {
    return
  }

  // Default to opening the URL from notification data
  const urlToOpen = notificationData?.url ?? '/'

  event.waitUntil(
    (async () => {
      // Try to find an existing client window
      const clientList = await self.clients.matchAll({
        type: 'window',
        includeUncontrolled: true,
      })

      // If we have a client, focus it and navigate
      for (const client of clientList) {
        if (client.url && 'focus' in client) {
          await client.focus()
          // Post message to navigate
          client.postMessage({
            type: 'NAVIGATE',
            url: urlToOpen,
          })
          return
        }
      }

      // Otherwise, open a new window
      await self.clients.openWindow(urlToOpen)
    })()
  )
})

// Handle notification close (dismissal)
self.addEventListener('notificationclose', (event: NotificationEvent) => {
  // Optionally track dismissals for analytics
  console.log('[SW] Notification closed:', event.notification.tag)
})

// ============================================================================
// MESSAGE HANDLING (from main app)
// ============================================================================

self.addEventListener('message', (event) => {
  const { type } = event.data || {}

  switch (type) {
    case 'SKIP_WAITING':
      self.skipWaiting()
      break

    case 'GET_VERSION':
      // Respond with the current service worker version
      event.ports[0]?.postMessage({
        type: 'VERSION',
        version: '1.0.0', // Could be dynamic based on build
      })
      break

    case 'SHOW_NOTIFICATION':
      // Show local notification from main thread (polling-based)
      {
        const { title, body, icon, data } = event.data
        const notificationOptions: ExtendedNotificationOptions = {
          body,
          icon: icon ?? '/icon-192.png',
          badge: '/icon-72.png',
          tag: data?.url ?? 'default',
          data,
          actions: data?.type === 'mention' || data?.type === 'reply'
            ? [
                { action: 'open', title: 'View' },
                { action: 'dismiss', title: 'Dismiss' },
              ]
            : data?.type === 'like' || data?.type === 'follow'
              ? [
                  { action: 'open', title: 'View Profile' },
                  { action: 'dismiss', title: 'Dismiss' },
                ]
              : undefined,
        }
        void self.registration.showNotification(title, notificationOptions)
      }
      break

    default:
      break
  }
})

// ============================================================================
// BACKGROUND SYNC (for offline support)
// ============================================================================

self.addEventListener('sync', ((event: SyncEvent) => {
  if (event.tag === 'sync-notifications') {
    event.waitUntil(syncNotifications())
  }
}) as EventListener)

async function syncNotifications(): Promise<void> {
  // This would sync with Bluesky API when back online
  // Implementation depends on your offline strategy
  console.log('[SW] Syncing notifications...')
}

// Log activation
self.addEventListener('activate', () => {
  console.log('[SW] Service Worker activated')
})

// Log installation
self.addEventListener('install', () => {
  console.log('[SW] Service Worker installing...')
})
